/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-22 18:19:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Datos.WrapperWikidata;
import Datos.WrapperPlayStore;
import Datos.WrapperAppstore;
import Modelo.Privacidad;
import Modelo.DatosDeUsuario;
import Modelo.App;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Datos.WrapperAppstore");
    _jspx_imports_classes.add("Modelo.App");
    _jspx_imports_classes.add("Modelo.Privacidad");
    _jspx_imports_classes.add("Datos.WrapperPlayStore");
    _jspx_imports_classes.add("Datos.WrapperWikidata");
    _jspx_imports_classes.add("Modelo.DatosDeUsuario");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"UTF-8\" />\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\" />\n");
      out.write("    <title>APPSPrivacity Consultor</title>\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/maicons.css\" />\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/bootstrap.css\" />\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/vendor/animate/animate.css\" />\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/theme.css\" />\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/style.css\" />\n");
      out.write("\n");
      out.write("    <!-- AppsDB icon -->\n");
      out.write("    <link rel=\"icon\" href=\"./assets/images/cloud-data-300.png\">    \n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("    <!-- Back to top button -->\n");
      out.write("    <div class=\"back-to-top\"></div>\n");
      out.write("    <header>\n");
      out.write("      <!-- NAVBAR -->\n");
      out.write("      <nav class=\"navbar navbar-toggleable-md navbar-light bg-faded\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("          <a href=\"index.jsp\" class=\"navbar-brand\">APPS<span class=\"text-primary\">Privacity</span></a>\n");
      out.write("        </div>\n");
      out.write("      </nav>\n");
      out.write("      <!-- NAVBAR -->\n");
      out.write("\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"page-banner\">\n");
      out.write("          <div class=\"row justify-content-center align-items-center h-100\">\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("              <div class=\"img-fluid text-center\">\n");
      out.write("                <img src=\"./assets/images/cloud-data-300.png\" alt=\"cloud-data image\"/>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"img-fluid text-center\" ><a href=\"#respuestas\" class=\"btn-scroll\" data-role=\"smoothscroll\">\n");
      out.write("                    <span class=\"mai-arrow-down\">Resultados</span></a></div>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <div class=\"page-section\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("\n");
      out.write("        <div class=\"row align-items-center\">\n");
      out.write("          <div class=\"col-lg-12 py-3\">\n");
      out.write("            <h2 class=\"title-section\">\n");
      out.write("              ¿Listo para preguntar?\n");
      out.write("              <span class=\"mai-bulb-outline\"></span>\n");
      out.write("            </h2>\n");
      out.write("            <div class=\"divider\"></div>\n");
      out.write("\n");
      out.write("            <!-- LOGIN FORM -->\n");
      out.write("            <form method=\"post\" action=\"Servlet\">\n");
      out.write("              <div class=\"form-group row text-left\">\n");
      out.write("                <label for=\"nameapp\" class=\"col-sm-4 col-form-label\"style=\"color: #8e44ad\">App:</label>\n");
      out.write("                <div class=\"col-sm-8\">\n");
      out.write("                  <input\n");
      out.write("                    type=\"name\"\n");
      out.write("                    name=\"name\"\n");
      out.write("                    class=\"form-control\"\n");
      out.write("                    id=\"name\"\n");
      out.write("                    placeholder=\"Enter app name\"\n");
      out.write("                  />\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"form-group row text-left\">\n");
      out.write("                <label for=\"SO\" class=\"col-sm-4 col-form-label\"style=\"color: #8e44ad\">Sistema Operativo:</label>\n");
      out.write("                 <label class=\"col-sm-4 col-form-label\"><input type=\"checkbox\" id=\"cbox1\" name=\"atributos\" value=Android> Android</label>\n");
      out.write("                 <label class=\"col-sm-4 col-form-label\"><input type=\"checkbox\" id=\"cbox2\" name=\"atributos\" value=iOS> iOS</label>\n");
      out.write("                </div>\n");
      out.write("              <div class=\"form-group row text-left\">\n");
      out.write("                <label for=\"SO\" style=\"color: #8e44ad\" class=\"col-sm-4 col-form-label\">Area:</label>\n");
      out.write("                <label class=\"col-sm-4  col-form-label\"><input type=\"checkbox\" id=\"cbox3\" name=\"atributos\" value=Mensajeria> Mensajeria</label>\n");
      out.write("                <label class=\"col-sm-4 col-form-label\"><input type=\"checkbox\" id=\"cbox4\" name=\"atributos\" value=Social> Social</label>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group row text-left\">\n");
      out.write("                <label for=\"SO\" class=\"col-sm-4 col-form-label\"style=\"color: #8e44ad\">Opciones:</label>\n");
      out.write("                <label class=\"col-sm-4 col-form-label\"><input type=\"checkbox\" id=\"cbox5\" name=\"atributos\" value=4> Información a terceros</label>\n");
      out.write("                <label class=\"col-sm-4 col-form-label\"><input type=\"checkbox\" id=\"cbox6\" name=\"atributos\"value=5> Publicidad en la app</label>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group row text-left\">\n");
      out.write("                <label for=\"SO\" class=\"col-sm-4 col-form-label\"style=\"color: #8e44ad\">Informacion de la empresa</label>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group row text-left\">\n");
      out.write("                <label class=\"col-sm-4 col-form-label\"><input type=\"checkbox\" id=\"cbox5\" name=\"atributos\" value=18> Nombre</label>\n");
      out.write("                <label class=\"col-sm-4 col-form-label\"><input type=\"checkbox\" id=\"cbox6\" name=\"atributos\"value=19> Nombre app</label>\n");
      out.write("                <label class=\"col-sm-4 col-form-label\"><input type=\"checkbox\" id=\"cbox6\" name=\"atributos\"value=20> URL</label>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group row text-left\">\n");
      out.write("                <label for=\"SO\" class=\"col-sm-4 col-form-label\"style=\"color: #8e44ad\">Datos que puede recopilar:</label>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group row text-left\">\n");
      out.write("                <label class=\"col-sm-4 col-form-label\"><input type=\"checkbox\" id=\"cbox9\" name=\"atributos\" value=6> Datos Contacto</label>\n");
      out.write("                <label class=\"col-sm-4 col-form-label\"><input type=\"checkbox\" id=\"cbox10\" name=\"atributos\" value=7> Credenciales</label> \n");
      out.write("                <label class=\"col-sm-4 col-form-label\"><input type=\"checkbox\" id=\"cbox11\" name=\"atributos\" value=8> Ubicacion</label>\n");
      out.write("                <label class=\"col-sm-4 col-form-label\"><input type=\"checkbox\" id=\"cbox12\" name=\"atributos\" value=9> Pagos</label> \n");
      out.write("                <label class=\"col-sm-4 col-form-label\"><input type=\"checkbox\" id=\"cbox13\" name=\"atributos\" value=10> Historial Busqueda</label>\n");
      out.write("                <label class=\"col-sm-4 col-form-label\"><input type=\"checkbox\" id=\"cbox14\" name=\"atributos\" value=11> Información de errores</label> \n");
      out.write("                <label class=\"col-sm-4 col-form-label\"><input type=\"checkbox\" id=\"cbox15\" name=\"atributos\" value=12> Multimedia</label> \n");
      out.write("                <label class=\"col-sm-4 col-form-label\"><input type=\"checkbox\" id=\"cbox16\" name=\"atributos\" value=13> Agenda</label>\n");
      out.write("                <label class=\"col-sm-4 col-form-label\"><input type=\"checkbox\" id=\"cbox17\" name=\"atributos\" value=14> Información de uso</label>\n");
      out.write("                <label class=\"col-sm-4 col-form-label\"><input type=\"checkbox\" id=\"cbox18\" name=\"atributos\" value=15> Idioma</label> \n");
      out.write("                <label class=\"col-sm-4 col-form-label\"><input type=\"checkbox\" id=\"cbox19\" name=\"atributos\" value=16> Información del dispositivo</label> \n");
      out.write("                <label class=\"col-sm-4 col-form-label\"><input type=\"checkbox\" id=\"cbox20\" name=\"atributos\" value=17> Salud</label> \n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group row text-left\">\n");
      out.write("                <label for=\"SO\" class=\"col-sm-4 col-form-label\"style=\"color: #8e44ad\">Resultados:</label>\n");
      out.write("                </div>\n");
      out.write("                ");
 
                    ArrayList<App> apps = (ArrayList<App>)request.getAttribute("output");
                    if(apps==null){
                        
      out.write("<output id=\"respuestas\">No existe respuesta para tu consulta</output>");

                    }else{
                       for(int i=0;i<apps.size();i++){
                            App app = apps.get(i);
                            if(app==null){
      out.write("\n");
      out.write("                             <output id=\"respuestas\">Los campos estan vacíos, seleccione algún atributo o introduzca nombre</output>\n");
      out.write("                            ");
}else{
      out.write("\n");
      out.write("\n");
      out.write("                              <output id=\"respuestas\">\n");
      out.write("                                  Nombre app: ");
      out.print( app.getName());
      out.write("<br>\n");
      out.write("                                  ");
if(app.getSO()!=""){
      out.write("Sistema Operativo: ");
      out.print( app.getSO());
}
      out.write("<br>\n");
      out.write("                                  ");
if(app.getArea()!=""){
      out.write("Sistema Area: ");
      out.print( app.getArea());
}
      out.write("<br>\n");
      out.write("                                  ");
if(app.getPrivacidad().getVersion()!=""){
      out.write("Informacion sobre privacidad:<br><label></label>");
}
      out.write("\n");
      out.write("                                  ");
if(app.getPrivacidad().getVersion()!=""){
      out.write(" Version:");
      out.print( app.getPrivacidad().getVersion());
      out.write(" <br><label></label>");
}
      out.write("\n");
      out.write("                                  ");
if(app.getPrivacidad().getInfTerceros()!=""){
      out.write("Información a terceros: ");
      out.print( app.getPrivacidad().getInfTerceros());
}
      out.write("<br><label></label>\n");
      out.write("                                  ");
if(app.getPrivacidad().getPubli()!=""){
      out.write("Publicidad ");
      out.print( app.getPrivacidad().getPubli());
}
      out.write("<br><label></label>\n");
      out.write("                                  ");
if(app.getEmpresa()!=null){
      out.write("\n");
      out.write("                                     Informacion sobre datos de empresa de la app: <br><label></label>\n");
      out.write("                                     ");
if(app.getEmpresa().getNombre()!=""){
      out.write("Nombre de la empresa: ");
      out.print( app.getEmpresa().getNombre());
      out.write("<br><label></label>");
}
      out.write("\n");
      out.write("                                     ");
if(app.getEmpresa().getNombre_app()!=""){
      out.write("Nombre de la app: ");
      out.print( app.getEmpresa().getNombre_app());
      out.write("<br><label></label>");
}
      out.write("\n");
      out.write("                                     ");
if(app.getEmpresa().getURL()!=""){
      out.write("URL de la app: ");
      out.print( app.getEmpresa().getURL());
      out.write("<br><label></label>");
}
      out.write("\n");
      out.write("                                  ");
}
      out.write("\n");
      out.write("                                  ");
if(app.getDatos()!=null){
      out.write("\n");
      out.write("                                   Informacion sobre datos de usuario que recopila: <br><label></label>\n");
      out.write("                                   ");
if(app.getDatos().getContacto()!=""){
      out.write("Información de contacto: ");
      out.print( app.getDatos().getContacto());
      out.write("<br><label></label>");
}
      out.write("\n");
      out.write("                                   ");
if(app.getDatos().getCredenciales()!=""){
      out.write("Información de credenciales: ");
      out.print( app.getDatos().getCredenciales());
      out.write("<br><label></label>");
}
      out.write("\n");
      out.write("                                   ");
if(app.getDatos().getDemografia()!=""){
      out.write("Información demografica: ");
      out.print( app.getDatos().getDemografia());
      out.write("<br><label></label>");
}
      out.write("\n");
      out.write("\n");
      out.write("                                   ");
if(app.getDatos().getPagos()!=""){
      out.write("Información de pagos: ");
      out.print( app.getDatos().getPagos());
      out.write("<br><label></label>");
}
      out.write("\n");
      out.write("                                   ");
if(app.getDatos().getHistorial_de_Busquedas()!=""){
      out.write("Información de historal de busqueda: ");
      out.print( app.getDatos().getHistorial_de_Busquedas());
      out.write("<br><label></label>");
}
      out.write("\n");
      out.write("                                   ");
if(app.getDatos().getInformes_de_Errores()!=""){
      out.write("Información errores: ");
      out.print( app.getDatos().getInformes_de_Errores());
      out.write("<br><label></label>");
}
      out.write("\n");
      out.write("\n");
      out.write("                                   ");
if(app.getDatos().getMultimedia()!=""){
      out.write("Información de multimedia: ");
      out.print( app.getDatos().getMultimedia());
      out.write("<br><label></label>");
}
      out.write("\n");
      out.write("                                   ");
if(app.getDatos().getAgenda()!=""){
      out.write("Información de agenda: ");
      out.print( app.getDatos().getAgenda());
      out.write("<br><label></label>");
}
      out.write("\n");
      out.write("                                   ");
if(app.getDatos().getInformacion_De_Uso()!=""){
      out.write("Información de uso: ");
      out.print( app.getDatos().getInformacion_De_Uso());
      out.write("<br><label></label>");
}
      out.write("\n");
      out.write("\n");
      out.write("                                   ");
if(app.getDatos().getIdioma()!=""){
      out.write("Información de idioma: ");
      out.print( app.getDatos().getIdioma());
      out.write("<br><label></label>");
}
      out.write("\n");
      out.write("                                   ");
if(app.getDatos().getInformacion_sobre_el_Dispositivo()!=""){
      out.write("Información del dispositivo: ");
      out.print( app.getDatos().getInformacion_sobre_el_Dispositivo());
      out.write("<br><label></label>");
}
      out.write("\n");
      out.write("                                   ");
if(app.getDatos().getFitness()!=""){
      out.write("Información sobre salud: ");
      out.print( app.getDatos().getFitness());
      out.write("<br><label></label>");
}
      out.write("\n");
      out.write("                                  ");
}
      out.write("\n");
      out.write("\n");
      out.write("                               </output>                           \n");
      out.write("                            ");
}
                        }
      out.write("\n");
      out.write("                    ");
}
      out.write("\n");
      out.write("               </div>  \n");
      out.write("               </div>  \n");
      out.write("              </div>\n");
      out.write("                           \n");
      out.write("              <!-- Button converted to a link for demonstration purposes only, in order to show the table management page for a logged-in user. -->\n");
      out.write("              <!-- <button type=\"submit\" class=\"btn btn-primary\">Login</button> -->\n");
      out.write("              <div class=\"row\">\n");
      out.write("                <div class=\"col-sm-12 text-center\">\n");
      out.write("                   <input type=\"submit\" class=\"btn btn-primary\" onclick=\"limpiar()\" value=\"Consultar\" name=\"consultar\">\n");
      out.write("                   <script>\n");
      out.write("                       function limpiar() {\n");
      out.write("                            document.getElementById(\"respuestas\").value = \"\";\n");
      out.write("                        }\n");
      out.write("                   </script>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("            </form>\n");
      out.write("            <!-- END LOGIN FORM -->\n");
      out.write("          </div>\n");
      out.write("          <!-- .col -->\n");
      out.write("        </div>\n");
      out.write("        <!-- .row -->\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- FOOTER -->\n");
      out.write("    <footer\n");
      out.write("      class=\"page-footer bg-image\"\n");
      out.write("      style=\"background-image: url(./assets/images/world_pattern.svg)\"\n");
      out.write("    >\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row mb-5\">\n");
      out.write("          <div class=\"col-lg-6 py-3\">\n");
      out.write("            <h3>APPS Privacity</h3>\n");
      out.write("            <p>\n");
      out.write("              Follow us on our social channels.\n");
      out.write("            </p>\n");
      out.write("\n");
      out.write("            <div class=\"social-media-button\">\n");
      out.write("              <a href=\"https://www.facebook.com/\"><span class=\"mai-logo-facebook-f\"></span></a>\n");
      out.write("              <a href=\"https://twitter.com/\"><span class=\"mai-logo-twitter\"></span></a>\n");
      out.write("              <a href=\"https://www.instagram.com/\"><span class=\"mai-logo-instagram\"></span></a>\n");
      out.write("              <a href=\"https://www.youtube.com/\"><span class=\"mai-logo-youtube\"></span></a>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("          <div class=\"col-lg-6 py-3\">\n");
      out.write("            <h5>Contact Us</h5>\n");
      out.write("            <p><a href=\"https://goo.gl/maps/Kr9kD6ZVdLPDxUTy8\" class=\"footer-link\">Inf-UVa, P.º de Belén, 15, 47011, Valladolid, Spain</a></p>\n");
      out.write("            <p><a href=\"tel:+34 123 45 67 89\" class=\"footer-link\">+34 123 45 67 89</a></p>\n");
      out.write("            <p><a href=\"mailto:saii@fake.email.com\" class=\"footer-link\">saii@fake.email.com</a></p>\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </footer>\n");
      out.write("    <!-- END FOOTER-->\n");
      out.write("\n");
      out.write("    <script src=\"./assets/js/jquery-3.5.1.min.js\"></script>\n");
      out.write("\n");
      out.write("    <script src=\"./assets/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("    <script src=\"./assets/vendor/wow/wow.min.js\"></script>\n");
      out.write("\n");
      out.write("    <script src=\"./assets/js/theme.js\"></script>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
